version: '3'

services:

  app:
    image: wordpress:php7.3-apache
    environment:
      WORDPRESS_DB_HOST: $WORDPRESS_DB_HOST
      WORDPRESS_DB_USER: $WORDPRESS_DB_USER
      WORDPRESS_DB_PASSWORD: $WORDPRESS_DB_PASSWORD
      WORDPRESS_DB_NAME: $WORDPRESS_DB_NAME
    volumes:
      - ./wp-content:/var/www/html/wp-content
    labels:
      traefik.http.routers.aa-berlin.rule: 'Host(`www.alcoholics-anonymous-berlin.de`)'
      traefik.http.routers.aa-berlin.tls: 'true'
      traefik.http.services.aa-berlin.loadbalancer.server.port: 80
      traefik.enable: true
